version: "3"

services:
  postgres:
    container_name: "postgres-website"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
