name: Deploy to VPS - Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch: # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "lts/hydrogen"

      - name: Deploy to VPS - Develop Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e

            # Verify Node.js version
            REQUIRED_NODE_VERSION=$(node -v | sed 's/^v//')
            INSTALLED_NODE_VERSION=$(ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "node -v | sed 's/^v//'")
            if [ "$REQUIRED_NODE_VERSION" != "$INSTALLED_NODE_VERSION" ]; then
              echo "Error: Node.js version mismatch. Required: $REQUIRED_NODE_VERSION, Installed: $INSTALLED_NODE_VERSION"
              exit 1
            fi

            # Check and install pm2 if not installed
            if ! ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "which pm2" > /dev/null; then
              echo "pm2 not found. Installing pm2..."
              ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "npm install pm2 -g"
            fi

            # Navigate to the project directory
            cd /var/www/develop/Bobagi-Website
            git reset --hard
            git pull origin develop

            # Build the website
            cd website
            npm ci
            npm run build

            # Install dependencies and restart the server
            cd ../server
            npm ci
            pm2 restart app.js --name site-backend-dev
