name: Deploy to VPS - Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "lts/hydrogen"

      - name: Install dependencies and build site
        run: |
          set -e
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to VPS - Develop Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            cd /var/www/develop/Bobagi-Website
            git reset --hard
            git pull origin develop
            npm install --legacy-peer-deps
            npm run build
